
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 15 17:07:40 CEST 2016
//----------------------------------------------------

package rs.ac.bg.etf.pp1.pd110349d;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 42;
  public static final int CONST = 8;
  public static final int LOG_OR = 19;
  public static final int L_PAREN = 27;
  public static final int SEMI = 5;
  public static final int R_PAREN = 28;
  public static final int GR_EQ_THAN = 32;
  public static final int MINUS = 36;
  public static final int STR_CONST = 44;
  public static final int COMMA = 4;
  public static final int CLASS = 6;
  public static final int INC = 17;
  public static final int DIV = 38;
  public static final int NUM = 41;
  public static final int PLUS = 35;
  public static final int ASSIGN = 3;
  public static final int IF = 15;
  public static final int DOT = 22;
  public static final int R_BRACKET = 26;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 29;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int L_CURLY = 23;
  public static final int MUL = 37;
  public static final int R_CURLY = 24;
  public static final int MOD = 39;
  public static final int IDENT = 40;
  public static final int BREAK = 11;
  public static final int GR_THAN = 31;
  public static final int VOID = 9;
  public static final int LE_EQ_THAN = 34;
  public static final int ELSE = 16;
  public static final int N_EQUAL = 30;
  public static final int READ = 13;
  public static final int WHILE = 10;
  public static final int EXTENDS = 7;
  public static final int PROG = 2;
  public static final int LOG_AND = 20;
  public static final int BOOL_CONST = 43;
  public static final int DEC = 18;
  public static final int LE_THAN = 33;
  public static final int L_BRACKET = 25;
  public static final int PRINT = 14;
}

